[2022-08-09 04:20:21,849] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: a_test.test_say_bye scheduled__2022-08-07T04:00:12.650445+00:00 [queued]>
[2022-08-09 04:20:22,194] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: a_test.test_say_bye scheduled__2022-08-07T04:00:12.650445+00:00 [queued]>
[2022-08-09 04:20:22,195] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-09 04:20:22,195] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-09 04:20:22,195] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-09 04:20:22,230] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): test_say_bye> on 2022-08-07 04:00:12.650445+00:00
[2022-08-09 04:20:22,277] {standard_task_runner.py:52} INFO - Started process 18946 to run task
[2022-08-09 04:20:22,283] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'a_test', 'test_say_bye', 'scheduled__2022-08-07T04:00:12.650445+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/var/folders/0s/6831mwss3ngbr2rh0337_18r0000gn/T/tmpp_hdj67p', '--error-file', '/var/folders/0s/6831mwss3ngbr2rh0337_18r0000gn/T/tmp8aenceg3']
[2022-08-09 04:20:22,285] {standard_task_runner.py:80} INFO - Job 70: Subtask test_say_bye
[2022-08-09 04:20:27,349] {task_command.py:371} INFO - Running <TaskInstance: a_test.test_say_bye scheduled__2022-08-07T04:00:12.650445+00:00 [running]> on host Fu-Changs-MacBook-Pro.local
[2022-08-09 04:20:32,417] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=anappleaday1984@gmail.com
AIRFLOW_CTX_DAG_OWNER=fu
AIRFLOW_CTX_DAG_ID=a_test
AIRFLOW_CTX_TASK_ID=test_say_bye
AIRFLOW_CTX_EXECUTION_DATE=2022-08-07T04:00:12.650445+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-07T04:00:12.650445+00:00
[2022-08-09 04:20:32,418] {logging_mixin.py:115} INFO - bye airflow
[2022-08-09 04:20:32,419] {python.py:173} INFO - Done. Returned value was: None
[2022-08-09 04:20:32,427] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=a_test, task_id=test_say_bye, execution_date=20220807T040012, start_date=20220808T202021, end_date=20220808T202032
[2022-08-09 08:50:26,798] {local_task_job.py:144} ERROR - Heartbeat time limit exceeded!
